import './index.css';
import { Inter } from "next/font/google"

const inter = Inter({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  variable: "--inter"
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased font-inter`}>{children}</body>
    </html>
  )
}
